my_git_repo_name:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: audwsqn-eo86859

      # User/password auth
      user: FIVETRAN_USER
      password: password123

      role: FIVETRAN_ROLE
      database: FIVETRAN_DATABASE
      warehouse: FIVETRAN_WAREHOUSE
      schema: dbo
      threads: 8
      client_session_keep_alive: False
      query_tag: TABLE
      

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false