
version: 2

models:
  - name: JOBS
    description: "A starter dbt model"
    columns:
      - name: JOB
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

